### ISSUE TITLE
Feature request for centercrop

### ISSUE THREAD

**Issue by hadaev8** [GaParmar/clean-fid#12]
My dataset has nonsquare samples, so on training, I'm doing random crop and for validation, I'm calculating fid with center cropped copy of dataset.
Would be cool to have some option for passing my own transform, for example.

**Comment by GaParmar** [comment]
Thank you for pointing out this use case, I will add this flag in the next version of the library.

**Comment by GaParmar** [comment]
this feature is available in the current clean-fid version 0.1.17
Any transforms can be passed in through the flag [`custom_image_tranform`](https://github.com/GaParmar/clean-fid/blob/main/cleanfid/fid.py#L409)
You can pass in a function that takes an image as an numpy array as input and returns the transformed image. For instance, the function below can be used to apply a crop to the images when computing the FID score. 
    
> ```
>     def fn_crop(x):
>         return x[60:-60, 60:-60, :]
>```

This option is only applied when the FID is computed between two folders.

**Comment by GaParmar** [comment]
Feel free to re-open this issue if you run into any issues with this.
