### ISSUE TITLE
Resolution in image folders

### ISSUE THREAD

**Issue by duongquangvinh** [GaParmar/clean-fid#2]
Hi,

I am a little confused that should the resolution of images in 2 folders be the same or different (folder1: 256x256, folder2: 1024x1024)? If not, can we use PIL to resize it or use torch transform resize?

Many thanks.

**Comment by GaParmar** [comment]
Hi, 

Can you provide some additional details about your use case?
The clean-fid will resize the images to expected size automatically. 
You should not need to resize the images manually. 

Regards,
Gaurav

**Comment by duongquangvinh** [comment]
Thank you for your reply.
I got this problem when running the code:

![Screenshot from 2021-06-22 09-39-56](https://user-images.githubusercontent.com/59604464/122854573-1a715480-d33e-11eb-8ee9-bf91b480d335.png)

How can i fix this? I try to do this on 256, 1024 resolution images but it always exposes this error.

**Comment by GaParmar** [comment]
Can you try 
```
score = fid.compute_fid(fdir1, fdir2, num_workers=0)
```

**Comment by duongquangvinh** [comment]
> Can you try
> 
> ```
> score = fid.compute_fid(fdir1, fdir2, num_workers=0)
> ```

It still doesn't work. The same error

**Comment by duongquangvinh** [comment]
I do not know that fdir1 and fdir2 should be both .npz or just a folder of images?

**Comment by GaParmar** [comment]
The fdir1 and fdir2 should be folder of images.
Can you try this colab notebook `https://colab.research.google.com/drive/1ElGAHvlwTilIf_3D3cw1boirCEkFsAWI?usp=sharing`

I just ran it and it doesn't give me the error.

**Comment by duongquangvinh** [comment]
![Screenshot from 2021-06-24 11-08-48](https://user-images.githubusercontent.com/59604464/123201309-9d301600-d4dc-11eb-9a44-2360b585ff58.png)

It just crashes the session. I do not know why? This is exactly what I met in my pc.

**Comment by GaParmar** [comment]
Could you try these changes that can cause the Segmentation Fault: 
- change num_workers=0
- decrease the batch size to be 1
- try running it on the CPU instead of the GPU to find the exact error message
- making sure that the PyTorch version installed is correct

**Comment by hangg7** [comment]
@GaParmar @duongquangvinh Hi guys, I have run into the same issue, and for my case it was bc of I usesd `torch==1.9.0`. Downgrading it to 1.8.0 makes the problem! Thanks

**Comment by GaParmar** [comment]
Hi @hangg7 

Thanks for pointing this out! 
This issue is related to this PyTorch JIT issue https://github.com/pytorch/pytorch/issues/64062 
I will update the clean-fid with a temporary fix for this soon. 

Regards,
Gaurav

**Comment by GaParmar** [comment]
This issue should be resolved in the current clean-fid version. 
Feel free to re-open it if you encounter this again.
