### ISSUE TITLE
open-cv is missing from the dependencies

### ISSUE THREAD

**Issue by felixdivo** [GaParmar/clean-fid#20]
However, it is required when using `fid.make_custom_stats()`. I used pip.

Also, the README instructs one to `pip install -r requirements.txt` while such a file is not present.

**Comment by GaParmar** [comment]
Hi, 

Thank you for pointing these issues! 
The Clean-FID should not require open-cv. 
In the previous versions there was unused import cv2 statement which caused this issue. 
The new version of the library 0.1.19 should address this issue. 

Regards,
Gaurav

**Comment by felixdivo** [comment]
![grafik](https://user-images.githubusercontent.com/4403130/150590209-713cea9b-ed6e-4ab2-bc47-dfe0b180d7d3.png)

Oh, seems like is was minutes out of date ... 🤣

**Comment by felixdivo** [comment]
Yup, seems like that solved it, thanks! 😄
