### ISSUE TITLE
Compute FID from generator doesn't fully respect num_gen

### ISSUE THREAD

**Issue by justinpinkney** [GaParmar/clean-fid#32]
Looks like the actual number of generations is rounded up to the nearest multiple of batch size: 

https://github.com/GaParmar/clean-fid/blob/fca67180659eae81d2ea207b11e12acd84735171/cleanfid/fid.py#L199

**Comment by GaParmar** [comment]
Thank you for pointing this out!
It should be correct in the recent version.

Cheers,
Gaurav
