### ISSUE TITLE
Why pinned requests==2.25.1?

### ISSUE THREAD

**Issue by aliencaocao** [GaParmar/clean-fid#42]
This version is pretty old...I just want to know why is it being pinned, as it conflicts with many of the other libraries I have.

**Comment by ZeroBomb** [comment]
As far I can tell, the only place the requests library is used is in the downloads_helper.py file, and the usage is pretty bog standard.  I see no reason to be that strict on requests version.

**Comment by GaParmar** [comment]
Thanks for pointing this out. I have changed the requests library requirement in the new version of the library.
