### ISSUE TITLE
A possible bug

### ISSUE THREAD

**Issue by hangg7** [GaParmar/clean-fid#7]
Hi Gaurav, thanks for sharing this amazing tool! I spot a block of suspicious lines that might worth your attention. Specifically, this resizing function of the default "clean" resizer:
https://github.com/GaParmar/clean-fid/blob/d2a10b1f4f44e79ea08717a10702fb1c674b1830/cleanfid/resize.py#L43-L52

It seems to me that the `output_size` in L47 (s1, s2) supposes to be a (w, h) tuple whilie L48 expects it as (h, w). What do you think? This might mean that the default resizer only works for square output resolution.

Shouldn't be a big problem since it does not affect default behavior.

**Comment by GaParmar** [comment]
Hi Hang, 

Thank you for pointing this out, I will address this in the next release and add more documentation here. 
However, this should not affect the FID behavior as the images are always resized to square output resolution 299x299. 

Regards,
Gaurav

**Comment by hangg7** [comment]
Thanks! Closing this now.
